travis:
  secure:
    BINSTAR_TOKEN: tCrKdCXdcSTs8E5aLmZsosatPc77LgQCAd0WRXUhWkvcpBbhuy/OhOCGSo1HSx55UShzVfWJJJsHZxmF1LOw8RGlV4hLnLyex+lMW8l2mBHLqzfy5OARypKgvIF16A3GpbK5JJzFF0SrgOnqNTgTR8IIcSZOV/Qgs8ecoLWAxp0d+AKhOVgDsCPRHZjbsY4CpCjby3mQlSQTVdTh1nnHirMx6GmzulC4uRUqowwfIoh6SGyfC3QRK80GafO0cfpPpXDJ0gmUN8d39MiBbOKXSeXLgJxNu7g46slav+ojHRll1AfhIIlVqd4BLJNbuKpTa8rzdO3yrNwuKjbHnCn5QPnDoqKwyx1mYfuWpfBgFhEnjXTpTkfDLkQmnWGmjH5kQNtbRW0m9VUw6ILaLvDX5O+0ZLbEEm8pTtOnHKbA8xkyRMbYdCIwSTSL2icP2or+rZxOGYcUPW5DKyGIw9+mQs/Bhu92M+/PK3KNYGJIaVI0wunOtTolPZiYFygTXIhTKoZoVcua4gzOsqsTC2XPosduPx3c3fSjZOVo/SFr8Ff97/34aJLGonSd8FRG8VnnNdhxXCgNiWZlAV8lSn/Wy0tysL4NsSUkBDBEC3H7iO+sUqDusyVY7dq1qLyhjfuMJHuAVB+s1C7nVL1NbxxtphITWLVEhbG2YN9RCg2r/R0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
